description: GCP Secret Manager
options:
  - name: secret_name
    description: Local secret name
    regex: "^[a-zA-Z][a-zA-Z_0-9]{0,32}$"
  - name: project_id
    description: GCP project ID
    regex: "^[a-zA-Z][a-zA-Z0-9_\\-]{0,32}$"
  - name: gcp_secret_name
    description: Name of secret in GCP Secrets manager (you should create it)
    regex: "^[a-zA-Z][a-zA-Z_0-9]{0,64}$"
filenames_replace:
  - regex: "^secret_name"
    replace_var_name: secret_name
help_message: |
  ###############################################################################
  # GCP Secret Manager cluster.dev secret example.                              #
  # cdev console tool generator                                                 #
  ###############################################################################
  To create and use the GCP secret:
  1) Login with your gcloud CLI: gcloud auth login
  2) use gcloud cli to crete secret: gcloud secrets create my_secret --replication-policy automatic
  3) To use this secret in the stack config use go-template reference: {{ .secret.secret_name.username }}.
  See usage examples in generated secret's comments
